development:
  host: <%= ENV['DRQUEUE_MASTER'] %>
  database: ipythondb

test:
  host: <%= ENV['DRQUEUE_MASTER'] %>
  database: ipythondb

production:
  host: <%= ENV['DRQUEUE_MASTER'] %>
  database: ipythondb
